### ISSUE TITLE
Refactor lib to C#

### ISSUE THREAD

**Issue by ghost** [ImaginaryDevelopment/PathOfSupporting#3]
Hi. 

Im help u coding this lib if U refactor to C#. 
F# insane for me. 

Thanks.

**Comment by ghost** [comment]
Im find new method. Very easy to parse item data. 

Use Nlua.

>             Lua state = new Lua();
            var success = true;
            try
            {
	            state.DoFile(@"C:\Users\WORK\Desktop\POE_Tools\MakeGearGreat\Demo\Demo\ModParser.lua");
            }
            catch (NLua.Exceptions.LuaScriptException e)
            {
	            success = false;
	            Console.WriteLine(e.ToString());
            }
            var scriptFunc = state ["parseMod"] as LuaFunction;

**Comment by ghost** [comment]
@ImaginaryDevelopment check this project https://github.com/jaspergould/PathOfSearching

**Comment by ImaginaryDevelopment** [comment]
k, moving it to C# won't happen.
